export enum ErrorCode {
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_UNAUTHORIZED = 'AUTH_UNAUTHORIZED',
  AUTH_FORBIDDEN = 'AUTH_FORBIDDEN',

  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  CONFLICT = 'CONFLICT',
  RATE_LIMITED = 'RATE_LIMITED',

  DB_CONSTRAINT = 'DB_CONSTRAINT',
  DB_NOT_AVAILABLE = 'DB_NOT_AVAILABLE',

  MAIL_DELIVERY_FAILED = 'MAIL_DELIVERY_FAILED',

  INTERNAL_ERROR = 'INTERNAL_ERROR',
}
