services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: booking-api
    depends_on:
      # db:
      #   condition: service_healthy
    # env_file:
    #   - .env.docker
    ports:
      - '4000:4000'
    restart: unless-stopped

volumes:
  pgdata:
  redisdata:
